name: WatchOS RHR Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: .build
          key: $-spm-$
          restore-keys: |
            $-spm-
            
    - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Build
        run: |
            xcode clean build project RHR.xcodeproj -scheme RHR Watch App -destination 'platform=watchOS Simulator, name=Apple Watch Series 10 (46mm), OS=latest'
    
    - name: Test
      run: |
        xcodebuild test -project RHR.xcodeproj -scheme RHR Watch App -destination 'platform=watchOS Simulator, name=Apple Watch Series 10 (46mm), OS=latest'

