name: WatchOS RHR Build

on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: macos-15
    strategy:
        matrix:
          device: ["Apple Watch Series 10 (46mm)"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: Select Xcode 16.0
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Check Xcode version
        run: xcodebuild -version

      - name: Build
        run: |
            xcodebuild clean build -project RHR.xcodeproj -scheme 'RHR Watch App' -destination 'platform:watchOS Simulator,OS:11.0,name:Apple Watch Series 10 (46mm)'

      - name: Test
        run: |
            xcodebuild test -project RHR.xcodeproj -scheme 'RHR Watch App' -destination 'platform:watchOS Simulator,OS:11.0,name:Apple Watch Series 10 (46mm)'

